### ISSUE TITLE
Individual States

### ISSUE THREAD

**Issue by hcps-larkinch** [Voter-Data-Project/PurpleAmerica#24]
![image](https://cloud.githubusercontent.com/assets/18335030/15624002/25509ac0-244b-11e6-9cb9-e9dd33d1825c.png)

First, does this scan get the specific state.txt file to draw the coordinates from that file rather than the country data file?

**Comment by hcps-larkinch** [comment]
Because if so, I don't understand why it would not pick up Hawaii and Alaska when drawing the individual states.

**Comment by SeanofLaRochelle** [comment]
I have code that handles the alaska file, but not code for Hawaii

**Comment by hcps-larkinch** [comment]
They are both in the data set.

**Comment by hcps-larkinch** [comment]
Well the problem with Hawaii is that the counties are area codes so the coding to draw that would have to change since it is constantly reading ints.

**Comment by SeanofLaRochelle** [comment]
Yeah, that why it doesn't work in the method used to draw the other states.

**Comment by SeanofLaRochelle** [comment]
Give me a sec to look at my code

**Comment by hcps-larkinch** [comment]
But why doesn't Alaska draw?

**Comment by SeanofLaRochelle** [comment]
So the stateName array gets the state names as the election data is pulled from the file. The array is later used to check to see if the state exists in the given year.

**Comment by SeanofLaRochelle** [comment]
And yes, if the user selects the state, the scanner will be directed to the individual states' files instead of the country file.

**Comment by hcps-larkinch** [comment]
I just realized the problem. So in the AK.txt file, Alaska has county names, but in the election data, the data is divided into districts rather than the county names. I don't know what to do to change that.

**Comment by SeanofLaRochelle** [comment]
That's why alaska always comes out black.

**Comment by hcps-larkinch** [comment]
I have no idea how to convert the  counties to districts. I don't know how I would determine that.

**Comment by SeanofLaRochelle** [comment]
to draw alaska just add this code 
                            if(state.equals("AK")){
                                xScale = 400;
                                map.setCanvasSize((int)xScale, 400);
                                //Handles if the user selects Alaska
                            }//End of if statement
under the 
                            double xScale = 400/((-1_yMin)-(-1_yMax)); //Sets the x relative to the state
                            xScale = xScale_(xMax-xMin); //_*Sets the x relative to the state

You will have to surround the other setCanvas statement under it with an else as so
                            else{
                                map.setCanvasSize((int)xScale, 650); //Sets the canvas size
                            }//End of else statement

**Comment by SeanofLaRochelle** [comment]
to draw alaska just add this code 

if(state.equals("AK")){
xScale = 400;
map.setCanvasSize((int)xScale, 400);
//Handles if the user selects Alaska
}//End of if statement

under the 

double xScale = 400/((-1yMin)-(-1yMax)); //Sets the x relative to the state
xScale = xScale(xMax-xMin); //*Sets the x relative to the state

You will have to surround the other setCanvas statement under it with an else as so

else{
map.setCanvasSize((int)xScale, 650); //Sets the canvas size
}//End of else statement

**Comment by SeanofLaRochelle** [comment]
Sorry github does not make this easy to show

**Comment by hcps-larkinch** [comment]
ok thank you so much

**Comment by SeanofLaRochelle** [comment]
Alaska should still come out black, but at least it draws
