### ISSUE TITLE
Issue #2 GUI Not Functioning

### ISSUE THREAD

**Issue by SeanofLaRochelle** [Voter-Data-Project/PurpleAmerica#6]
The GUI will not pop up when the program runs. The issue is a result of the program having a different main method. The main method and the GUI file need to be combined and the current main method needs to be removed. The GUI also needs to be able to change the variables that affect the outcome of the map.

**Comment by hcps-chatterjs** [comment]
Could you put the code in here instead so I can compare what's going on?

**Comment by hcps-chatterjs** [comment]
I also started working on it a bit and also saw the merged files in our repository. I think I can get the menu to work by Monday, but if you have any changes, create another issue or create another pull request.
