### ISSUE TITLE
#4 Having trouble with having different pen sizes for choosing the location highlighted. 

### ISSUE THREAD

**Issue by hcps-chatterjs** [Voter-Data-Project/PurpleAmerica#8]
Problem: The pen size is already set, but what I'm trying to do for my functionality is try to get the person to highlight the location(coordinates) on the map and open another JFrame that draws that specific map ( cant't decide either state or county). But right now, running it will have a small size of .002 that is used to draw the map itself. I want to keep the .002 pen size to draw the map, but when the user clicks, I want to have a bigger point size. I have attached the file code as well.

![prob](https://cloud.githubusercontent.com/assets/18405675/15080202/fcc8db56-138a-11e6-98d4-a20e350645e2.PNG)
![prob1](https://cloud.githubusercontent.com/assets/18405675/15080203/fcc99c08-138a-11e6-9171-89d7d5da4000.PNG)

package map;
import edu.princeton.cs.introcs._;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
/_*
 *
- @hcps-chatterjs 
  */
  public class PoliticalMap {
  public static void main(String[] args) throws FileNotFoundException{;
      File file = new File("C:\Users\hcps-chatterjs\Documents\FIFA II\New     FOrk\PurpleAmerica1\src\data\USA-county.txt");
      Scanner scan = new Scanner(file);
      StdDraw.setCanvasSize(1200, 650);
      StdDraw.setPenRadius(0.002);
      StdDraw.setPenColor(Color.green);
      double xMin = scan.nextDouble();
      double yMin = scan.nextDouble();
      double xMax = scan.nextDouble();
      double yMax = scan.nextDouble();
      int regionNum = scan.nextInt();
      StdDraw.setXscale(xMin, xMax);
      StdDraw.setYscale(yMin, yMax);
      double[] xVal;
      double[] yVal;
      int pointNum = 0;
  
  ```
  for(int i = 0; i < regionNum; i++){
      if(scan.hasNextInt() == true){
          pointNum = scan.nextInt();
          xVal = new double[pointNum];
          yVal = new double[pointNum];
          for(int j = 0; j < pointNum; j++){
             xVal[j] = scan.nextDouble();
             yVal[j] = scan.nextDouble();
          }
          StdDraw.polygon(xVal, yVal);
          StdDraw.point(StdDraw.mouseX() , StdDraw.mouseY());
      }
      else{
          i = i - 1;
          scan.next();
      }
  }
  while(true) {
      if(StdDraw.mousePressed()) {
          System.out.println(StdDraw.mouseX() + " " + StdDraw.mouseY());
          StdDraw.point(StdDraw.mouseX() , StdDraw.mouseY());
  
          try {
              Thread.sleep(1000);
          } catch(InterruptedException ex) {
              Thread.currentThread().interrupt();
          }
      }
  }
  ```
  
  }

}

**Comment by cmneville** [comment]
Great Issue here... Someone help this man out!  If the problem was already solved then close it

**Comment by SeanofLaRochelle** [comment]
I will take a look at the issue this weekend. A new version of the program has been placed in the repository.
